//! Keyboard + mouse input actions for Tribes.
//! Uses leafwing-input-manager with serde-serializable Action enum.
//! Gamepad/Xbox NOT supported.

use bevy::prelude::Reflect;
use leafwing_input_manager::Actionlike;

#[derive(
    Actionlike,
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    serde::Serialize,
    serde::Deserialize,
    Reflect,
)]
pub enum GameAction {
    MoveForward,
    MoveBackward,
    StrafeLeft,
    StrafeRight,
    Ski,
    Jetpack,
    Fire,
    Aim,
    ActivateMelee,
    ActivateBelt,
    ActivatePack,
    Reload,
    Use,
    SpotTarget,
    ShowScores,
    SwitchWeapon1,
    SwitchWeapon2,
    SwitchWeapon3,
    SwitchWeapon4,
    SwitchWeapon5,
    SwitchWeapon6,
    SwitchWeapon7,
    SwitchWeapon8,
    SwitchWeapon9,
    SwitchWeapon10,
    CallIn1,
    CallIn2,
    CallIn3,
    CallIn4,
    CallIn5,
    CallIn6,
    ClassPathfinder,
    ClassSentinel,
    ClassInfiltrator,
    ClassSoldier,
    ClassRaider,
    ClassTechnician,
    ClassJuggernaut,
    ClassDoombringer,
    ClassBrute,
    DropFlag,
    BehindView,
    VoteYes,
    VoteNo,
    ToggleChat,
    ToggleScores,
    Suicide,
    ZoomToggle,
    ZoomMagnify,
    ZoomDemagnify,
}