edition = "2024"
max_width = 100
use_field_init_shorthand = true
use_try_shorthand = true

# Nightly-only options (we use fenix nightly)
imports_granularity = "Module"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100
